// Generated by CoffeeScript 1.8.0
window.carrega = function(url, processa) {
  var request;
  request = new XMLHttpRequest();
  request.open('GET', "../assets/" + url, true);
  request.responseType = 'arraybuffer';
  request.onload = function() {
    return window.context.decodeAudioData(request.response, function(theBuffer) {
      var source;
      alert("Carregado " + url);
      source = window.context.createBufferSource();
      source.buffer = theBuffer;
      source.connect(window.context.destination);
      return processa(source);
    });
  };
  return request.send();
};
