// Generated by CoffeeScript 1.8.0
window.init = function(callback) {
  window.contextClass = window.AudioContext || window.webkitAudioContext || window.mozAudioContext || window.oAudioContext || window.msAudioContext;
  if (contextClass) {
    window.context = new contextClass();
    alert("Context loaded");
    if (callback) {
      return callback();
    }
  } else {
    alert("BZIU!");
    if (callback) {
      return callback();
    }
  }
};
