// Generated by CoffeeScript 1.8.0
window.init = function() {
  var context;
  window.contextClass = window.AudioContext || window.webkitAudioContext || window.mozAudioContext || window.oAudioContext || window.msAudioContext;
  if (contextClass) {
    return context = new contextClass();
  } else {
    return alert("BZIU!");
  }
};
