// Generated by CoffeeScript 1.8.0
var osc;

osc = function(type, freq, detune) {
  var oscillator;
  oscillator = context.createOscillator();
  oscillator.connect(context.destination);
  oscillator.frequency.value = freq;
  oscillator.detune.value = detune;
  oscillator.type = type === "sine" || type === "sawtooth" || type === "triangle" || type === "square" ? type : alert("Not valid oscillator");
  return oscillator.start(0);
};

window.sine = function(freq, detune) {
  return osc("sine", freq, detune);
};

window.saw = function(freq, detune) {
  return osc("sawtooth", freq, detune);
};

window.tri = function(freq, detune) {
  return osc("triangle", freq, detune);
};

window.saw = function(freq, detune) {
  return osc("square", freq, detune);
};
