// Generated by CoffeeScript 1.8.0
window.osc = function(type, freq, detune) {
  var oscillator;
  oscillator = window.context.createOscillator();
  oscillator.connect(window.context.destination);
  oscillator.frequency.value = freq;
  oscillator.detune.value = detune;
  oscillator.type = type === "sine" || type === "sawtooth" || type === "triangle" || type === "square" ? type : alert("Not valid oscillator");
  alert("" + type + ": freq: " + freq + " detune:" + detune);
  oscillator.start(0);
  return oscillator;
};

window.sin = function(freq, detune) {
  return osc("sine", freq, detune);
};

window.saw = function(freq, detune) {
  return osc("sawtooth", freq, detune);
};

window.tri = function(freq, detune) {
  return osc("triangle", freq, detune);
};

window.sqr = function(freq, detune) {
  return osc("square", freq, detune);
};
