// Generated by CoffeeScript 1.8.0
window.show = function(a, b) {
  alert($("#" + a).html());
  return $(document).ready(function() {
    return $("body").append(function() {
      return $("<pre></pre>").append(function() {
        return $("<code></code>").html($("#" + a).html());
      });
    });
  });
};
